### ISSUE TITLE
可以加一个自动签到的功能吗

### ISSUE THREAD

**Issue by MarshuMax** [left0ver/github-bbdc-stat#1]
Hi Author, 非常有趣的项目！另外可以再加一个不背自动签到的功能吗

**Comment by left0ver** [comment]
很遗憾，这个项目并不适用于不背单词自动签到，签到的一些功能需要登录和post请求，对于这样的一个项目来说行不通

**Comment by left0ver** [comment]
> Hi Author, 非常有趣的项目！另外可以再加一个不背自动签到的功能吗
很遗憾，这个项目并不适用于不背单词自动签到，签到的一些功能需要登录和post请求，对于这样的一个项目来说行不通

**Comment by MarshuMax** [comment]
OK, thank you
